app = "unicorn-galaxy-frontend"
primary_region = "sjc"

[build]

[env]
  LISTEN_PORT = "8080"
  SERVER_HOST = "unicorn-galaxy-recorder.internal"
  SERVER_PORT = "8083"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
