services:
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    # This doesn't have a namespace because it's a local image.
    # I should consider namespacing my self-built images.
    image: owntracks-broker
    environment:
      # These are development values only. In production, they are secrets.
      - MQTT_USERNAME=owntracks
      - MQTT_PASSWORD=owntracks
    ports:
      - 1883:1883
    restart: unless-stopped

  frontend:
    image: owntracks/frontend
    depends_on:
      - recorder
    environment:
      - LISTEN_PORT=8080
      - SERVER_HOST=recorder
      - SERVER_PORT=8083
    ports:
      - 8080:8080
    volumes:
      # The docs don't make it clear that this is required. When this file is
      # missing, I get a browser error.
      - ./frontend/config.js:/usr/share/nginx/html/config/config.js
    restart: unless-stopped

  recorder:
    image: owntracks/recorder
    depends_on:
      - broker
    environment:
      - OTR_HOST=broker
      - OTR_PORT=1883
      # These are development values only. In production, they are secrets.
      - OTR_PASS=owntracks
      - OTR_USER=owntracks
    # ports:
    #   # I don't need to expose this port on the host. This is just for
    #   # development.
    #   - 8083:8083
    volumes:
      - config:/config
      - store:/store
    restart: unless-stopped

volumes:
  store:
  config:
