app = "unicorn-galaxy-recorder"
primary_region = "sjc"

[build]
  image = "owntracks/recorder:latest"

[env]
  OTR_HOST = "unicorn-galaxy-mqtt.internal"
  OTR_PORT = "1883"
  OTR_HTTPHOST = "[::]"
  OTR_HTTPPORT = "8083"

[mounts]
  source = "unicorn_galaxy_recorder"
  destination = "/store"
  initial_size = "10gb"
